- .semaphoreci/setup.sh
- Dockerfile
- integration/resources/build/Dockerfile
> Migrate to go 1.13

- .travis.yml
Disable documentation publish with travis
> Fix documentation ci - disable for now

- .goreleaser.yml
- .travis.yml
- Makefile
- tmpl.Dockerfile
This PR adds [seihon](https://github.com/ldez/seihon) that build and publish multi-arch images on the Docker Hub.
Fixes: #206
> Add seihon for multi arch build

- helm/chart/maesh/charts/metrics/Chart.yaml
- helm/chart/maesh/charts/metrics/templates/grafana.yaml
- helm/chart/maesh/charts/metrics/templates/prometheus.yaml
There ware some old, internal links stell set in the helm chart. This PR is cleaning that up.
> Rename some legacy links

- Makefile
- docs/scripts/netlify-run.sh
This PR fix the custom domain for documentation.
> Fix CNAME for documentation

- .semaphoreci/setup.sh
- integration/coredns_test.go
- integration/integration_test.go
- integration/kubernetes_test.go
- integration/resources/compose/k3s.yaml
- integration/resources/coredns/coredns.yaml
- integration/smi_test.go
- internal/k8s/client.go
This PR adds support for CoreDNS 1.5 and 1.6
Fixes #207
> Add support of coredns 1.5 and 1.6 

- .semaphoreci/job1.sh
- Makefile
- helm/chart/maesh/charts/metrics/Chart.yaml
- helm/chart/maesh/charts/metrics/templates/grafana.yaml
- helm/chart/maesh/charts/metrics/templates/prometheus.yaml
- helm/chart/maesh/requirements.yaml
This PR fix Namespace name in the metrics chart.
> Fix helm chart metrics version

- README.md
Add badges and links to the doc and license in the README.
> Add few links & badges to README

- README.md
Yep, a good way to get more commits on this project.
> Fixing my mistakes

- helm/chart/maesh/Chart.yaml
> Fix helm version

- helm/chart/maesh/Chart.yaml
Prepare release v0.2.1
Create a new release.
> Prepare release v0.2.1

- cmd/configuration.go
- cmd/maesh/maesh.go
- helm/chart/maesh/templates/controller/controller-deployment.yaml
- helm/chart/maesh/values.yaml
- internal/controller/controller.go
- internal/k8s/ignore.go
- internal/k8s/ignore_test.go
- internal/providers/smi/provider_test.go
This one fixes #220 :)
There is know a new option to ignore "namespaces"
> add static configuration option for ignore namespaces

- helm/chart/maesh/Chart.yaml
Prepare release v0.3.0
Create a new release.
> Prepare release v0.3.0

- helm/chart/maesh/charts/metrics/Chart.yaml
- helm/chart/maesh/charts/tracing/Chart.yaml
- helm/chart/maesh/requirements.yaml
- helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
- helm/chart/maesh/values.yaml
- integration/resources/values.yaml
This PR improves the way we manage metrics and tracing for maesh.
> Improve metrics and tracing chart

- go.mod
- go.sum
- helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
- helm/chart/maesh/values.yaml
- integration/integration_test.go
- integration/resources/values.yaml
- internal/providers/kubernetes/provider.go
- internal/providers/kubernetes/provider_test.go
This PR upgrades to traefik v2.0
> Migrate to traefik 2.0

- helm/chart/maesh/Chart.yaml
Prepare release v0.4.0
Create a new release.
> Prepare release v0.4.0

- internal/k8s/client.go
> Check the coredns pod volumes for being a configmap

- helm/chart/maesh/charts/metrics/templates/prometheus.yaml
- helm/chart/maesh/charts/metrics/values.yaml
- helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
- helm/chart/maesh/values.yaml
> image-names can be defined for all helm-charts

- helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
Partially fixes #265 
This will allow the correct default values to be set
> Check for Jaeger values set or take default

- internal/controller/controller.go
- internal/deployer/deployer.go
- internal/providers/base/base.go
- internal/providers/kubernetes/provider.go
- internal/providers/smi/provider.go
- internal/providers/smi/provider_test.go
This PR
- Removes configuration state from the controller
- Moves more base provider code to the base package
Fixes #242
> Remove Configuration state from controller

- helm/chart/maesh/Chart.yaml
Get all the awesome stuff released!
> Prepare release 0.5.0

- helm/chart/maesh/Chart.yaml
Prepare release v0.6.0
Create a new release.
> Prepare release v0.6.0

- .golangci.toml
- internal/providers/smi/provider.go
This PR:
- Reduces the CI gocyclo to 15
- Small refactor to SMI provider to reduce complexity
Fixes #272
> Reduce Gocyclo to 15

- internal/controller/controller.go
This PR:
- Creates a timer to deploy to unready nodes, even if configuration hasn't changed
- Checks each container in a pod to determine readiness
Fixes #290 
Fixes #292
> Deploy to unready nodes

- Makefile
- integration/integration_test.go
This PR upgrade hem to version v2.15.1
Fixes #295
> Upgrade helm to version 2.15.1

- helm/chart/maesh/templates/_helpers.tpl
- helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
- helm/chart/maesh/values.yaml
- integration/integration_test.go
- integration/resources/values.yaml
> Add tag from values, default to v2.0

- cmd/configuration.go
- cmd/prepare/prepare.go
- docs/content/install.md
- helm/chart/maesh/charts/metrics/templates/grafana.yaml
- helm/chart/maesh/templates/controller/controller-deployment.yaml
- helm/chart/maesh/templates/dns/coredns/coredns-configmap.yaml
- helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
- helm/chart/maesh/values.yaml
- internal/k8s/client.go
Fixes #278 
- add new variable `clusterDomain` to chart
- use variable instead of hard coded `cluster.domain`
> make cluster domain configurable

- helm/chart/maesh/Chart.yaml
> Prepare Release 0.7.0

- .semaphoreci/job2.sh
- Makefile
- integration/integration_test.go
This PR:
- Pins k3s version
- Moves k3d install to makefile
Fixes #316 
Fixes #311
> Pin k3s version

- docs/content/api.md
- docs/mkdocs.yml
- internal/controller/api.go
This PR:
- Adds API documentation for the newly added Controller API
The documentation can be viewed via the netlify preview 😄 
Fixes #327
> Add API documentation

- helm/chart/maesh/Chart.yaml
This PR:
- Prepares for v0.8.0 Release
> Prepare Release v0.8.0

- docs/content/install.md
This PR:
- Adds platform recommendations
- Asks for testing on a recommended platform if issues are encountered
- Recommends k3s for dev/testing
Fixes #318
> Add platform recommendations

- docs/content/quickstart.md
This PR updates the quickstart guide to add a `using maesh` section, demonstrating how to use maesh.
Fixes: #323 
Check netlify deployment and run this quickstart guide.
> Add demo example in the quickstart guide

- helm/chart/maesh/Chart.yaml
This PR Prepares for GA release v1.0.0!
> Prepare Release v1.0.0

- docs/content/install.md
This PR:
- Updates the documentation to reflect updated SMI configuration options
Fixes #366
> Update Doc for CRD deployment

- helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
- helm/chart/maesh/values.yaml
- integration/resources/values.yaml
This PR:
- Adds datadog tracing to Maesh
Works towards #369
> Add datadog tracing

- helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
- helm/chart/maesh/values.yaml
- integration/resources/values.yaml
This PR:
- Adds Datadog Metrics capabilities to Maesh
Works towards #368
> Add datadog metrics

- helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
- helm/chart/maesh/values.yaml
This PR:
- Adds Zipkin to Tracing
- Adds Instana to Tracing
- Adds Haystack to Tracing
Fixes #369 
Fixes #202
> Add zipkin/instana/haystack to tracing

- helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
- helm/chart/maesh/values.yaml
This PR:
- Adds InfluxDB to metrics
- Adds StatsD to metrics
Fixes #368 
Fixes #329 
Fixes #65
> Add influxDB and statsD to metrics

- docs/check.Dockerfile
This PR:
- Fixes travis `not get uid/gid` error
Based on https://github.com/containous/traefik/pull/5971
> Fix Travis Builds

- helm/chart/maesh/templates/_helpers.tpl
- integration/integration_test.go
Fixes #387 
I bumped the integ tests as well as the Pod Image. Not really sure what you mean by api @dtomcej ? There have been no changes on the REST API for v2.1 iirc?
> Update Traefik to 2.1

- docs/content/configuration.md
- internal/k8s/constants.go
- internal/providers/base/base.go
- internal/providers/base/base_test.go
> Add Configuration to use HTTPS as scheme

- .travis.yml
> Add Versioned docs

- helm/chart/maesh/Chart.yaml
This PR Prepares for RC release v1.1.0-rc1
> Prepare release v1.1.0-rc1

- .travis.yml
This PR:
- Fixes an issue with a nested chart directory
> Fix chart directory

- CONTRIBUTING.md
> Document release process & steps

- docs/content/configuration.md
> Add a note about being a namespaced ressource

- internal/providers/smi/provider.go
> Enhance logging to show expects for TCPRoute and HTTPRoute

- helm/chart/maesh/Chart.yaml
This PR Prepares for RC release v1.1.0-rc2
> Prepare release v1.1.0-rc2

- README.md
This PR:
- Updates the semaphoreCI badge after switch to v2
> Update SemaphoreCI Badge

- pkg/controller/controller.go
- pkg/controller/handler.go
- pkg/controller/service.go
- pkg/controller/service_test.go
- pkg/k8s/client.go
- pkg/providers/base/base.go
- pkg/providers/kubernetes/provider.go
- pkg/providers/smi/provider.go
This PR introduces the ShadowServiceManager type, which decouple shadow service management from the controller.
closes #426 
Co-authored By: Harold Ozouf harold.ozouf@gmail.com
> Shadow service manager

- .semaphore/semaphore.yml
- .travis.yml
This PR:
- Adds the `semaphore.yml` to the gh-pages branch in travisCI
- Adds a skip condition in the `semaphore.yml` file for the gh-pages branch
Fixes #448
> Fix CI for gh-pages branch

- go.mod
- go.sum
- integration/smi_test.go
- integration/try/try.go
- pkg/api/api.go
- pkg/api/api_test.go
- pkg/api/fixtures/getmeshnodeconfiguration_simple.yaml
- pkg/api/fixtures/getmeshnodes_one_mesh_pod.yaml
- pkg/api/fixtures/getmeshnodes_one_nonready_mesh_pod.yaml
- pkg/controller/api_test.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/controller/fixtures/getmeshnodeconfiguration_simple.yaml
- pkg/controller/fixtures/getmeshnodes_one_mesh_pod.yaml
- pkg/controller/fixtures/getmeshnodes_one_nonready_mesh_pod.yaml
- pkg/controller/fixtures/mock.yaml
- pkg/deploylog/log.go
- pkg/deploylog/log_test.go
- pkg/k8s/client.go
- pkg/k8s/client_mock.go
- pkg/k8s/constants.go
- pkg/providers/kubernetes/provider.go
- pkg/providers/smi/provider.go
This PR:
- Moves from structs to interfaces for clients
- Adds fixture based unit tests for API
- Adds fixture based unit tests for Controller
- Moves API to its own package
- Moves DeployLog to its own package
- Adds interfaces for API and Deploylog
Fixes #343 
Fixes #341 
Fixes #351
> Move to client interfaces, and create fixture tests for API and Controller

- internal/providers/kubernetes/fixtures/build_configuration_multiple_targetports.yaml
- internal/providers/kubernetes/fixtures/build_configuration_multiple_targetports_mixture.yaml
- internal/providers/kubernetes/fixtures/build_configuration_multiple_targetports_mixture_tcp.yaml
- internal/providers/kubernetes/fixtures/build_configuration_multiple_targetports_tcp.yaml
- internal/providers/kubernetes/provider.go
- internal/providers/kubernetes/provider_test.go
This PR:
- Fixes TargetPort misdirection
- Adds test for Targetports:
- HTTP
- TCP
> Allow for TargetPorts

- helm/chart/maesh/Chart.yaml
> Prepare Release v1.1

- .goreleaser.yml
- helm/chart/maesh/Chart.yaml
- pkg/providers/kubernetes/fixtures/build_configuration_multiple_targetports.yaml
- pkg/providers/kubernetes/fixtures/build_configuration_multiple_targetports_mixture.yaml
- pkg/providers/kubernetes/fixtures/build_configuration_multiple_targetports_mixture_tcp.yaml
- pkg/providers/kubernetes/fixtures/build_configuration_multiple_targetports_tcp.yaml
- pkg/providers/kubernetes/provider.go
- pkg/providers/kubernetes/provider_test.go
This PR:
Updates the master branch with the updates from v1.1
> Mergeback v1.1.0

- cmd/maesh/maesh.go
- cmd/prepare/prepare.go
- integration/try/try.go
- pkg/controller/controller.go
- pkg/k8s/client.go
- pkg/prepare/prepare.go
This PR:
- Adds a FieldLogger interface to the following packages:
- Prepare
- k8s client
- Controller
Further logging updates will be needed, but will be done in a follow up PR
Works towards fixing #464
> Use logrus.FieldLogger for logging

- pkg/api/api.go
- pkg/api/api_test.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/controller/handler.go
- pkg/controller/service.go
- pkg/controller/service_test.go
- pkg/deploylog/log.go
- pkg/deploylog/log_test.go
- pkg/providers/kubernetes/provider.go
- pkg/providers/kubernetes/provider_test.go
- pkg/providers/smi/provider.go
- pkg/providers/smi/provider_test.go
This PR:
- Implements the logrus.FieldLogger interface into the remaining packages
Fixes #464
> Implement the rest of the logger interfaces

- .semaphore/semaphore.yml
This PR:
- Updates Go to 1.14
Fixes #443
> Update to Go 1.14

- pkg/controller/service.go
This PR:
- Checks the kubernetes version, and adds a service topology key if supported by the server.
Fixes #385
> Add service topology key logic

- pkg/controller/controller.go
- pkg/provider/provider.go
- pkg/provider/provider_test.go
This PR removes the dependency from the provider to a topology builder, by making `BuildConfig` take a topology directly.
This means that it's now the controller's responsibility to call the topology builder and to pass that configuration to the provider.
* `make test-integration` should still work as expected
* `make test` should also work
> Remove dependency from provider to topology builder

- README.md
This PR adds the [Go Report Card](https://goreportcard.com/) badge for Maesh to the readme.
> Add Go report card badge to readme

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
This PR:
- Updates the PR and Bug report templates
Fixes #518 
Also updated the community forum link.
> Update github templates

- pkg/controller/service.go
> Add more topology keys

- integration/acl_enabled_test.go
> Remove unneeded Helm install

- pkg/controller/controller.go
- pkg/k8s/client.go
- pkg/k8s/client_mock.go
- pkg/prepare/prepare.go
- pkg/provider/provider.go
- pkg/topology/builder.go
- pkg/topology/builder_test.go
- pkg/topology/topology.go
This PR injects errors in the resource handle by the topology.
Fixes #522
> Inject errors in topology

- docs/content/compatibility.md
- docs/mkdocs.yml
Adds a simple compatibility section.
Fixes #512
> Add simple compatibility section

- helm/chart/maesh/Chart.yaml
> Prepare Release v1.2

- .travis.yml
This PR:
- Increases the goreleaser build timeout fo fix the failing release build.
> Increase goreleaser build timeout

- .goreleaser.yml
This PR:
- Backports d83028e to master.
> Disable non-used builds

- pkg/prepare/prepare.go
This PR:
- Removes the Preparer interface
Fixes #583
> Remove Preparer interface

- helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
- helm/chart/maesh/values.yaml
This PR:
- Adds forwardingTimeouts to the helm chart
Fixes #577
> Add forwardingTimeouts

- helm/chart/maesh/templates/controller/controller-deployment.yaml
- helm/chart/maesh/values.yaml
This PR:
- Comment optional Helm options.
- Move root Maesh options to the beginning of the file.
- Move important mesh and controller options to the start of the corresponding property.
> Refactor and clean Helm chart options

- cmd/cleanup/cleanup.go
- cmd/configuration.go
- cmd/log.go
- cmd/maesh/maesh.go
- cmd/prepare/prepare.go
- docs/content/configuration.md
- helm/chart/maesh/templates/controller/controller-deployment.yaml
- helm/chart/maesh/templates/controller/hooks/cleanup-hook.yaml
- helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
- helm/chart/maesh/values.yaml
This PR:
- Allows for json logging by adding a formatter to the logger
Fixes #561
> Add json logger

- cmd/maesh/maesh.go
- pkg/controller/controller.go
This PR:
- Adds error handling to the informer startup
Fixes #607
> Add error handling to the informer startup

- pkg/topology/builder.go
This PR:
- Renames confusing variables and method for a loop detection method
Fixes #586
Maps are pointers. Sometimes I hate golang.
> Rename method and vars for loop removal

- cmd/maesh/maesh.go
This PR:
- Fixes a bug preventing the controller to gracefully shutdown on SIGTERM or SIGINT.
Fixes #627
* Build and start Maesh binary.
* Send SIGTERM or SIGINT signals with: `kill -SIGTERM pid` or `kill -SIGINT pid`.
* Controller should exit gracefully.
> Gracefully shutdown controller on SIGTERM or SIGINT

- docs/content/install.md
- pkg/provider/provider.go
This PR: Improve logging clarity for provider.go. This will give a better understanding to debug issue #599
- Reproduce the linked issue
or
- `make test`
> Improve log clarity about missing pod keys for provider

- pkg/topology/builder.go
- pkg/topology/builder_test.go
- pkg/topology/testdata/topology-service-with-pod-port-mixture.json
This PR:
- Dedupes the service pods indexed in the topology.
Fixes #649
* make test
> Dedupe the service pods indexed in the topology

- helm/chart/maesh/Chart.yaml
- helm/chart/maesh/charts/metrics/Chart.yaml
> Prepare Release v1.3

- helm/chart/README.md
- helm/chart/maesh/Chart.yaml
> Prepare Release v1.3.1

- helm/chart/maesh/Chart.yaml
> Prepare Release v1.3.2

- docs/content/examples.md
This PR:
- Fixes an inconsistency in the example page of the documentation.
Fixes #683
> Fix inconsistency in the example page of the documentation

- .travis.yml
This PR:
- adds. mixtus for documentation publication.
> Add mixtus for documentation

- pkg/dns/dns.go
- pkg/dns/dns_test.go
- pkg/dns/testdata/configurecoredns_17_already_patched.yaml
- pkg/dns/testdata/configurecoredns_17_custom_already_patched.yaml
This PR:
- Checks if the corefile has changed before updating the coredns deployment
* make test
> Always update CoreDNS deployment in prepare phase

- docs/content/examples.md
- docs/content/quickstart.md
- integration/acl_disabled_test.go
- integration/acl_enabled_test.go
- integration/coredns_test.go
- integration/kubedns_test.go
- integration/testdata/acl_disabled/http/1.server.yaml
- integration/testdata/acl_disabled/tcp/1.server.yaml
- integration/testdata/acl_disabled/traffic-split/2.server-v1.yaml
- integration/testdata/acl_disabled/traffic-split/3.server-v2.yaml
- integration/testdata/acl_disabled/udp/1.server.yaml
- integration/testdata/acl_enabled/http/1.server.yaml
- integration/testdata/acl_enabled/http/3.server-api.yaml
- integration/testdata/acl_enabled/http/4.server-header.yaml
- integration/testdata/acl_enabled/traffic-split/1.server-split.yaml
This PR:
- Adds a version tag to the whoami images.
> Add version tag to whoami images

- helm/chart/mesh/Chart.yaml
This PR:
Prepare release for v1.4.0-rc1
> Prepare v1.4.0-rc1

- .travis.yml
This PR fixes documentation deployment.
> Fix documentation deployment

- integration/acl_disabled_test.go
- integration/coredns_test.go
- integration/kubedns_test.go
- integration/testdata/kubedns/coredns.yaml
- integration/testdata/traefik-mesh/controller-acl-disabled.yaml
- integration/testdata/traefik-mesh/controller-acl-enabled.yaml
- integration/testdata/traefik-mesh/proxy.yaml
- pkg/dns/dns.go
- pkg/dns/dns_test.go
- pkg/dns/testdata/configurecoredns_17_already_patched.yaml
- pkg/dns/testdata/configurecoredns_17_custom_already_patched.yaml
- pkg/dns/testdata/configurecoredns_already_patched.yaml
- pkg/dns/testdata/configurecoredns_custom_already_patched.yaml
- pkg/dns/testdata/restorecoredns_custom_not_patched.yaml
- pkg/dns/testdata/restorecoredns_custom_patched.yaml
- pkg/dns/testdata/restorecoredns_patched.yaml
- pkg/dns/testdata/restorekubedns_already_patched.yaml
- pkg/provider/rule.go
- pkg/provider/testdata/acl-disabled-http-basic-config.json
- pkg/provider/testdata/acl-disabled-http-traffic-split-config.json
- pkg/provider/testdata/acl-enabled-http-basic-config.json
- pkg/provider/testdata/acl-enabled-http-route-group-config.json
- pkg/provider/testdata/acl-enabled-http-traffic-split-config.json
- pkg/provider/testdata/acl-enabled-http-traffic-split-http-route-group-config.json
- pkg/provider/testdata/annotations-scheme-config.json
This PR removes the support of the `Maesh` domain.
* make test
> Remove maesh domain support

- cmd/loaders.go
This PR removes the support of maesh env and config files.
* make test
> Remove support of maesh env and config files

- .golangci.toml
- .semaphore/semaphore.yml
- Dockerfile
- cmd/mesh/mesh.go
- integration/k3d/k3d.go
- integration/try/condition.go
- integration/try/try.go
- pkg/annotations/annotations_test.go
- pkg/annotations/middleware.go
- pkg/k8s/client.go
- pkg/provider/provider.go
- pkg/topology/builder.go
This PR:
- enables docker hub authentication
- upgrades golangci-lint
> Docker authentication

- docs/content/examples.md
What does this PR do?
- This PR this fixed documentation about ACL example
- Port changed from string to number
Fixes #778
How to test it
- make test
- make test-integration
> Fix ACL example

- .golangci.toml
- .semaphore/semaphore.yml
- Dockerfile
- cmd/mesh/mesh.go
- docs/content/examples.md
- integration/k3d/k3d.go
- integration/try/condition.go
- integration/try/try.go
- pkg/annotations/annotations_test.go
- pkg/annotations/middleware.go
- pkg/controller/service.go
- pkg/controller/service_test.go
- pkg/dns/dns.go
- pkg/dns/dns_test.go
- pkg/dns/testdata/checkdnsprovider_supported_version_suffix.yaml
- pkg/k8s/client.go
- pkg/provider/provider.go
- pkg/topology/builder.go
This PR:
- Merges current v1.4 branch into master
* make test
> Merge current v1.4 branch into master

- .github/workflows/documentation.yml
- .travis.yml
Replace Travis CI by GitHub Action to build and publish the documentation.
Have a stable publication process.
~~- [ ] Added/updated tests~~
> Use github Action to build and publish documentation

- .github/workflows/documentation.yml
This PR adds seo support for mesh
Manage seo stuff in the documentation
- ~~[ ] Added/updated tests~~
- ~~[ ] Added/updated documentation~~
> Add seo support

- Makefile
- docs/check.Dockerfile
- integration/k3d/k3d.go
This PR:
- Adds missing packages for the `html-proofer` installation
- Update tooling dependency versions
> Fix html-proofer installation

- .semaphore/semaphore.yml
This PR fixes the semaphore release jobs.
> ci: fix release workflow

- docs/requirements.txt
This PR updates the mkdocs dependency version.
> chore: update mkdocs dependency version

- docs/content/examples.md
This PR fixes the non-working `TCPRoute` and `TrafficTarget` in the ACL example.
> Fix TCPRoute and TrafficTarget config in ACL example

- LICENSE
- docs/mkdocs.yml
> Update copyright for 2022

- Dockerfile
- docs/check.Dockerfile
- docs/docs.Dockerfile
Update base alpine image to v3.15
> Update alpine base image to v3.15
