traefik/mesh

docs/CNAME
docs/content/assets/styles/extra.css
docs/content/index.md
docs/mkdocs.yml
docs/scripts/netlify-run.sh
docs/theme/main.html

This PR introduces the following changes:
- Enable Google Tag Manager for enabling analytics for visitors
- Fix the header bar: set the logo on a bigger size and hide the title (as the logo is the same text, but decorated)
- Reword index page according to that was set on the Dockerhub

Documentation Polish for public release

---

.gitignore
.travis.yml
Makefile

This PR introduces the following changes:
- Main Documentation is generated on branches and deployed to gh-pages
- We'll be able to use `structor` for versionned documentation in the future
- Helm charts are mixed with documentation
- New docs and helm packaging makefile goals
Motivation is that we want to keep Netlify only for pull requests, while centralizing the "production" hosting of both `docs.mae.sh` and the helm chart on a single github page website.

Host main documentation on gh-pages, mixed with Helm Chart

---

docs/check.Dockerfile
docs/docs.Dockerfile
docs/requirements.txt

This PR introduces the following changes on the documentation tooling:
- Bump base image of Docker images for documentation  to Alpine `3.10`
- Bump `html-proofer` to latest stable `3.12.0`
- Faster documentation verification and linting: using native `nokogiri` in the alpine containers instead of building it, thanks to the Alpine Linux 3.10 bump.
- Bump `markdownlint` (and `markdownlint-cli`) versions to get latest changes from <https://github.com/markdownlint/markdownlint/blob/master/CHANGELOG.md#v040-2016-08-22>
- Bump `mkdocs` dependencies to their latest minor versions
Motivations:
- Faster documentation builds
- Chore on the dependencies

Update documentation tooling

---

.golangci.toml
Dockerfile
Makefile
cmd/configuration.go
integration/try/try.go
internal/controller/controller.go
internal/controller/handler.go
internal/deployer/deployer.go
internal/k8s/client.go
internal/k8s/client_mock.go
internal/k8s/constants.go
internal/message/message.go
internal/providers/smi/provider.go

This PP upgrades golangci lint to `v1.18.0` to be compatible with go 1.13

Upgrade to golanci-lint v1.18.0

---

helm/chart/maesh/templates/mesh/mesh-daemonset.yaml

The maesh daemonset is not being scraped by prometheus because of missing annotations. This PR adds the annotation to add the metrics to the prometheus instance.

fix: maesh daemonset is not scraped by prometheus

---

helm/chart/maesh/templates/controller/controller-deployment.yaml
helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
helm/chart/maesh/values.yaml

In our environment, we lock down deployments on the node using nodeSelector and certain tolerations. I added the sections so that we can configure and control on which nodes (like an operations set of nodes).

Added nodeselector, tolerations and affinity to deployments and daemonsets

---

docs/content/quickstart.md

Add instructions on how to configure the `default` ServiceAccount on
the `kube-system` namespace so it acts as a `cluster-admin`.
While not recommended for production, it's good enough to give maesh a
try on an isolated environment.
Fixes: https://github.com/containous/maesh/issues/225

Add note about tiller RBAC on the quickstart guide

---

helm/chart/maesh/charts/metrics/Chart.yaml
helm/chart/maesh/charts/metrics/templates/grafana.yaml
helm/chart/maesh/charts/metrics/templates/prometheus.yaml
helm/chart/maesh/charts/tracing/Chart.yaml
helm/chart/maesh/requirements.yaml

Performing liveness/readiness probes on endpoints other than
health/ready can cause unexpected results, and depending on
the Kubernetes version further problems depending on the size of
the response.
In particular, starting from Kubernetes 1.16 the limit of these
responses have been restricted to 10KB [1]. Thus, on Kubernetes 1.16
and beyond, Grafana was never marked as ready with the default maesh
deployment.
[1] https://github.com/kubernetes/kubernetes/pull/76518

Improve grafana and prometheus liveness and readiness probes

---

docs/content/index.md
docs/content/install.md
helm/chart/maesh/templates/hooks/coredns.yaml
helm/chart/maesh/templates/hooks/prepare-hook.yaml
helm/chart/maesh/values.yaml
integration/coredns_test.go
integration/integration_test.go
integration/kubedns_test.go
integration/kubernetes_test.go
integration/resources/kubedns/kubedns.yaml
integration/resources/values.yaml
integration/smi_test.go
internal/k8s/client.go
internal/k8s/client_mock.go

This PR adds support for kubedns.
If KubeDNS is detected in the kubernetes cluster and coredns is not installed. Maesh will install CoreDNS as a DaemonSet and will patch KubeDNS to add a stubDomains that forward all dns request with prefix `.maesh` to the coreDNS instances.

Add support for kubedns

---

helm/chart/maesh/templates/_helpers.tpl
helm/chart/maesh/templates/controller/controller-deployment.yaml

This PR makes it possible, to manage multiple namespaces to ignore in a more "listable" Style
```controller:
ignoreNamespaces: 
- local-path-storage
- some-other
```

Make Ignorenamespaces better manageable

---

integration/smi_test.go
internal/controller/controller.go
internal/k8s/client.go
internal/k8s/client_mock.go
internal/providers/kubernetes/fixtures/build_configuration_simple_http_middlewares.yaml
internal/providers/kubernetes/fixtures/build_configuration_simple_tcp.yaml
internal/providers/kubernetes/provider.go
internal/providers/kubernetes/provider_test.go

This PR:
- modifies the Kubernetes provider to be stateless.
- reduces the number of kubernetes api calls by selecting objects first, then looping through them in-memory
- moves base config building to the provider, from the controller.
Partially solves #242.

Move to stateless Kubernetes Provider

---

Dockerfile
cmd/maesh/maesh.go
cmd/prepare/prepare.go
integration/coredns_test.go
integration/integration_test.go
integration/smi_test.go
integration/try/try.go
internal/controller/controller.go
internal/deployer/deployer.go
internal/k8s/client.go
internal/k8s/client_mock.go
internal/k8s/namespace.go
internal/k8s/service.go
internal/message/message.go
internal/providers/kubernetes/provider.go
internal/providers/smi/provider.go
internal/providers/smi/provider_test.go
internal/signals/signal.go

This PR updates golangci-lint to 1.20.0
`wsl` is enabled.
Deal with it.

Update golangci-lint to 1.20.0

---

internal/providers/kubernetes/provider.go

This PR fix a panic
```console
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x120 pc=0x106563a]
goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:58 +0x105
panic(0x126c1a0, 0x1ecb5d0)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/containous/maesh/internal/providers/kubernetes.(*Provider).buildService(0xc000354300, 0x0, 0xc000836678, 0x3, 0xc000764600)
/go/src/github.com/containous/maesh/internal/providers/kubernetes/provider.go:75 +0x3a …
```

Fix panic when deeting a ns

---

internal/controller/controller.go
internal/controller/handler.go
internal/k8s/constants.go

This PR:
- Consolidates Informer Factories and handlers
- Updates the config Chan to allow forced deploys
Fixes #286

Deploy configuration to mesh pods even if config hasn't changed

---

helm/chart/maesh/charts/metrics/templates/grafana.yaml
helm/chart/maesh/charts/metrics/templates/prometheus.yaml
helm/chart/maesh/charts/tracing/templates/jaeger-deployment.yaml
integration/resources/coredns/coredns.yaml
integration/resources/tools/deployment.yaml
integration/resources/whoami/whoami.yaml

This PR:
Removes the deprecated extensions/v1beta1 API group.
From: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
This allows installation in k8s 1.16.
Fixes #277

Remove deprecated extensions/v1beta1 API group

---

Dockerfile
Makefile
integration/integration_test.go
integration/resources/whoami/whoami.yaml

This Pr upgrades golangci-lint version to v1.21.0 and fix helm version to v2.14.3
Fixes #300

Upgrade golangci-lint and fix helm version

---

.golangci.toml

golangci-lint has replaced `deadline` by `timeout`
Fixes #308

fix: linter timeout.

---

helm/chart/maesh/charts/metrics/templates/grafana.yaml
helm/chart/maesh/charts/metrics/templates/prometheus.yaml
helm/chart/maesh/charts/tracing/templates/jaeger-deployment.yaml

The K8s API version `apps/v1` made the `spec.selector` field required for deployments. This PR adds values for the missing selectors.
Fixes #305

add spec.selector field to Helm chart dependencies

---

.semaphoreci/job2.sh
Makefile

This PR:
- Removes the docker based `make test-integration`
- Renames the local integration test to `make test-integration`
So that we don't have 2 separate integration test paths

Remove local-test-integration

---

helm/chart/maesh/templates/mesh/mesh-daemonset.yaml

This PR:
- Moves liveness probe to dedicated and named entrypoint
- Prepares for liveness logic in the future
- Removes the liveness port from the HTTP/TCP limits
Fixes #307

Move liveness to dedicated entrypoint

---

internal/controller/controller.go
internal/controller/handler.go
internal/k8s/ignore.go
internal/k8s/ignore_test.go
internal/k8s/namespace.go
internal/providers/kubernetes/provider.go
internal/providers/kubernetes/provider_test.go
internal/providers/smi/provider.go
internal/providers/smi/provider_test.go

This PR:
- Refactors `ignoreWrapper` to be more dynamic
- Prepares code for non-maesh namespaces
Fixes #289

Refactor ignorewrapper

---

internal/controller/controller.go

This PR:
- Re-adds the `kube-system` namespace to the ignored list
Fixes #324

Re-add ignored namespace

---

cmd/configuration.go
cmd/maesh/maesh.go
go.mod
helm/chart/maesh/templates/controller/controller-deployment.yaml
integration/integration_test.go
internal/controller/api.go
internal/controller/controller.go

This PR:
- Creates an API handler with 2 listeners:
- "/api/configuration/current"
- "/api/status/readiness"
- Exposes the Last Deployed Configuration
- Allows for configurable API port (default 9000)
- Uses the API to have a readiness endpoint
- Tune readiness to be ready after successful deploy of configuration
- Configures deployment to use the new readiness endpoint
- Makes controller not ready errors clearer in the CI, rather than just failing a random test
Fixes #171 
Fixes #321

Create API on the controller

---

docs/content/examples.md
docs/content/install.md
docs/content/quickstart.md
docs/mkdocs.yml

Fixes #267 
Fixes #319 
Fixes #269 
This PR adds an example page to the documentation, with YAML snippets of example services.
It also adds a link in the quickstart page to the examples page, as well as adds the prerequisites to the documentation, in the install page (they were only in the README.md before and not in the doc)
* `cd docs ; make serve`
* Ensure that links are working
* Ensure that notes and command blocks (and their tabs) are working
* Look out for typos etc.

Add examples to doc

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE/pull_request.md

Fixes #339 
This PR adds a PR template for the Maesh project, and updates the issue template to remove the unnecessary whitespaces at the beginning of each line.
* Read it and ensure that it makes sense and fits the project
* Look out for typos

Add PR template

---

go.sum
internal/controller/api.go
internal/controller/api_test.go
internal/controller/controller.go
internal/controller/log.go
internal/controller/log_test.go

This PR:
- Creates a deployLog
- Logs successful and failed deployments to mesh pods
- Creates an API endpoint to list the log
Fixes #331

Create a deploy log and wire to API

---

internal/controller/api.go
internal/controller/api_test.go
internal/controller/controller.go

This PR:
- Adds `/api/status/nodes` endpoint to list nodes, IPs and readiness status
- Adds `/api/status/node/xxx/configuration` endpoint to query the configuration from the pod name in the query
Example:
```
[{"Name":"maesh-mesh-dddzh","IP":"10.1.0.141","Ready":true}]
```
```
{"routers":{"b-default-80-1630c62929f8593e@rest":{"entryPoints":["http-5000"],"service":"b-default-80-1630c62929f8593e","rule":"Host(`b.default.maesh`) || Host(`10.110.234.23`)","status":"enabled","using":["http-5000"]},"compose-ap-docker-443-1a055e3db30bd9d5@rest":{"entryPoints":["http-5000"],"service":"compose-ap-docker-443-1a055e3db30bd9d5","rule":"Host(`compose-api.docker.maesh`) || Host(`10.96.62.229`)","status":"enabled","using":["http-5000"]},"d-default-80-2329da148b27c5c4@rest":{"entryPoints":["http-5000"],"s …
```

Add Cluster Node Status and Configuration endpoints

---

go.mod
go.sum
internal/controller/controller.go

This PR makes the maesh controller deploy dynamic configuration in parallel.
Fixes: #244
- I'm relying on `golang.org/x/sync/errgroup` which is equivalent to `sync.WaitGroup` but cleaner. Is it OK ? 
- Each deployment goroutine applies a backoff with an hardcoded max elapsed time of ~1 minute~ 15 seconds. ~Do we want to make this configurable ?~
- I unattached `deployToPod` from  the Controller as it does not depend on any members of this struct. WDYT? 
- ~Opened as a draft 'cuz I'm not quite done testing :sweat_smile:~

Deploy to pods in parallel

---

internal/controller/api.go
internal/controller/api_test.go
internal/controller/controller.go
internal/controller/log.go
internal/controller/log_test.go

This PR:
- Creates a log rotation scheme where old records are removed
- Adds tests to ensure the rotation works
Fixes #334

Create a cap for the max number of deploy log entries

---

docs/content/configuration.md
docs/content/install.md

This PR adds documentation about installing and using Maesh with SMI enabled.
Fixes #320 
Check Netlify deployment.
Installation in SMI mode is based on the changes to the helm chart introduced in #346.

Document Maesh and SMI

---

netlify.toml

Signed-off-by: dduportal <1522731+dduportal@users.noreply.github.com>
Result:
```bash
curl -I https://deploy-preview-362--maesh-doc.netlify.com/
HTTP/2 200 
strict-transport-security: max-age=31536000; includeSubDomains; preload;
```

Enforce HSTS with netlify toml config

---

internal/providers/kubernetes/provider.go
internal/providers/smi/provider.go

This PR fixes #358 by doing the following changes:
In `smi/provider.go`:
* Verify that endpoints are non-nil before accessing their subsets
* Verify that address target references are non-nil before accessing their name/namespace
* Verify that tcpStateTables are non-nil before accessing their table
In `kubernetes/provider.go`
* Verify that tcpStateTables are non-nil before accessing their table
Use the configuration files provided in the issue #358 in the provider unit tests and ensure that they pass. It should not be the case with the current state of master.
This PR will most likely be blocking for the next PR I plan on making, which introduces a unit test of building a TCP configuration in the SMI provider. It's while building the configuration that I found the issues described here, …

Fix panics in SMI & Kubernetes provider

---

helm/chart/maesh/templates/controller/controller-deployment.yaml
helm/chart/maesh/templates/smi/smi-access.yaml
helm/chart/maesh/templates/smi/smi-spec.yaml
helm/chart/maesh/templates/smi/smi-trafficsplits.yaml
helm/chart/maesh/values.yaml
integration/integration_test.go
integration/resources/values.yaml

Fixes #217 
That PR adds the option to install the SMI CRD's together with the normal installation of maesh.

Bundle SMI CRD's with helm install

---

helm/chart/maesh/templates/controller/controller-deployment.yaml
helm/chart/maesh/templates/mesh/mesh-service.yaml
internal/controller/controller.go
internal/controller/handler.go
internal/k8s/client.go
internal/k8s/ignore.go
internal/k8s/ignore_test.go
internal/k8s/namespace.go
internal/providers/kubernetes/provider.go
internal/providers/kubernetes/provider_test.go
internal/providers/smi/provider.go
internal/providers/smi/provider_test.go

This PR makes Maesh able to run in a single namespace.
Fixes: #253 
Install maesh in the same namespace of your applications, and enjoy your shiny service mesh  as usual :tada:
Now, all generated mesh services are labeled with `app=maesh` too.
Then the controller is now able to a list of apps, right now `maesh` and `jaeger` are hardcoded, and we might want to change that. But it makes maesh ignore the maesh services. 
For the initial `createMaeshService` I used  [fields selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/#supported-operators) instead of filtering everything in memory.
I also made the filtering more time efficient using a map instead of iterating over the services, as we can have a lot of services this can be important. 
I kind of …

Run in single namespace

---

helm/chart/maesh/Guidelines.md
helm/chart/maesh/charts/metrics/templates/grafana.yaml
helm/chart/maesh/charts/metrics/templates/prometheus.yaml
helm/chart/maesh/charts/metrics/templates/storage.yaml
helm/chart/maesh/charts/metrics/values.yaml
helm/chart/maesh/values.yaml

This PR:
* fixes some typos in Guidlines.md
* makes it possible to pass StorageClassName to Grafana/Prometheus in the metrics subchart
* makes it possible to pass resource requests/limits to the metrics subchart (the default requests were pretty high, especially for Prometheus)
Fixes #360

Make metrics subchart more configurable

---

helm/chart/maesh/charts/metrics/templates/grafana.yaml
helm/chart/maesh/charts/metrics/templates/prometheus.yaml

When using Maesh with minikube the first time you run `helm install --name=maesh --namespace=maesh` everthing works nice. But minikube being a local development thingy it is quite common to `minikube stop` the cluster and then `minikube start` it again. Also known as rebooting. :wink: 
After the reboot the grafana and prometheus pods would not start and report some permission error. After digging around a while I figured the pods are run with a specific uid/gid and the volumes are mounted with root user id.
I'm not sure if I have provided a workaround or an actual fix. Maybe this PR needs more polishing. If so, please let me know.

Use initContainers to fix volume permissions

---

helm/chart/maesh/templates/dns/coredns/coredns-configmap.yaml
integration/kubernetes_test.go
integration/resources/whoami/0-namespace.yaml
integration/resources/whoami/0-namespaces.yaml
integration/resources/whoami/whoami-test.yaml
integration/smi_test.go
internal/controller/controller.go
internal/k8s/client.go

This PR:
- Uses a custom separator `-shadow-service-` instead of `-` to separate name and namespace
- Adds integration tests to ensure dashes in names and namespaces work
Fixes #378

Use custom separator for service name and namespace

---

README.md
docs/content/install.md

Fixes #392 
The installation of the chart will fail with Helm v3. Adding a temporary note might make things clearer.

Add a note about helm v2

---

internal/providers/smi/provider_test.go

This PR:
- Reworks a test condition so that the contents of a slice are checked to exist, rather than the slice explicitly being equal.
Kubernetes does not guarantee results are returned in any order, and therefore we can end up with the same list of objects in a different order.
This is not equal in golang, but is equal for kubernetes, and therefore we can relax our testing to ensure that the results are the same length, and that they contain all of our expected elements.
Fixes #397

Rework test condition

---

cmd/configuration.go
cmd/prepare/prepare.go
helm/chart/maesh/templates/controller/controller-deployment.yaml
integration/integration_test.go
integration/resources/smi/access-control-broken/1.tts.yaml
integration/smi_test.go
internal/k8s/client.go

This PR:
- Adds an informer sync test to the prepare command to ensure that the informers will start when the controller starts.
This prevents a situation where the controller starts, but the sync doesn't occur, and the result is empty listers that create empty configurations.
Fixes #413

Add informer sync test to prepare command

---

integration/smi_test.go
internal/providers/smi/provider.go
internal/providers/smi/provider_test.go

This PR:
- Updates the rule construction to be in goregexp format, as required by Traefik (https://docs.traefik.io/v2.1/routing/routers/#rule)
This is becuase the PathMatch field is a user-provided regex, but it will not be in goregexp format.
Fixes #414

Update regex rule for HTTPRouteGroup

---

Makefile
docs/content/building.md

This PR:
- Adds `TESTFLAGS` env var, which can allow individual suites to be run
This PR prepares the way for parallel integration test runs.
Fixes #405

Allow single test suites to be run

---

.semaphore/semaphore.yml
.semaphore/setup.sh
Makefile

This PR:
- Adds the configuration for Semaphore v2, with the suites running independently
There will be performance improvements to be made regarding building/running/caching and such, but for the time being, it can reduce our ~10 minute CI runs to ~5 minutes-ish, with much faster fails.
The other benifit of keeping test runs short is that they are much easier to debug, since you aren't waiting 6 minutes for a test to fail. This is why I have not ported over any retry functionality.
We should fix failing tests instead of just running them again.
I tried doing some build - cache - test, but I couldn't get it to work much faster without reworking the whole build/test process, which might be a goal moving forward.

Setup semaphore v2

---

internal/providers/kubernetes/fixtures/build_configuration_multiple_ports.yaml
internal/providers/kubernetes/fixtures/build_configuration_multiple_ports_tcp.yaml
internal/providers/kubernetes/provider.go
internal/providers/kubernetes/provider_test.go

This PR:
- Ensures that the correct endpoints on the proxy service are used.
Because we were not checking the intended port in the loop, it added all the ports for all endpoints, not only the ones we wanted.
Fixes #423

Ensure only correct port endpoints get added to proxy service

---

integration/integration_test.go

This PR addresses a bug discovered by @dtomcej while running integration tests.
SMI integration tests were failing because we weren't waiting for the cluster to be ready before starting the tests.
k3d provides the `--wait <seconds>` option to wait for the cluster to come up before returning. An error will be returned if it takes more than <seconds>.
The timeout has been set to 30 seconds.
Fixes: #434

Wait fort the k3s cluster to come up before running tests

---

Makefile

This PR:
- Updates k3d to 1.5.1, which uses k3s 1.17
This PR paves the way for dev on #385

Update k3s to use k8s 1.17

---

go.sum
integration/smi_test.go
integration/try/try.go

This PR:
- Adds waiting functionality for Pod IPs so that we don't create partial configurations.
This should hopefully reduce the failure rate of the SMI provider.
Fixes #434 
I hope.

Wait for Pod IPs to be assigned in Integration test

---

cmd/configuration.go
cmd/maesh/maesh.go
integration/integration_test.go
pkg/controller/api.go
pkg/controller/api_test.go
pkg/controller/controller.go

This PR:
- Adds the ability to define a host/IP for the API to bind to, not just ports.
Fixes #404 
This prevents warnings and error popups on Mac integration tests (and some unit tests)

Add host to API bind

---

pkg/controller/controller.go
pkg/controller/handler.go
pkg/controller/service.go
pkg/controller/service_test.go
pkg/k8s/tcpportmapping.go
pkg/k8s/tcpportmapping_test.go

This PR updates the `ShadowServiceManager` to cleanup the TCPPortMapping before a shadow service get updated or deleted. This way, we can reuse HTTP and TCP ports when a Service gets updated. 
Fixes: https://github.com/containous/maesh/issues/442
How to reproduce the issue:
- Install Maesh on a cluster with the following static configuration: 
```
helm install maesh helm/chart/maesh --namespace=maesh --set controller.image.pullPolicy=IfNotPresent --set controller.image.name=maesh-dev --set controller.image.tag=latest --set limits.tcp=2 --set limits.http=2
```
- Deploy a TCP server and a Service:
```
---
kind: Deployment
apiVersion: apps/v1
metadata:
name: whoami-tcp-server
namespace: whoami
spec:
selector:
matchLabels:
app: whoami-tcp-server
replicas: 2
template:
metadata:
labels:
app: …
```

Cleanup TCPPortMapping when updating/deleting a shadow service

---

.travis.yml

This PR:
- Creates the missing directory before copying the semaphore yml:
https://travis-ci.com/containous/maesh/builds/151743572#L867
Hopefully fixes #448, and fixes master branch CI

Add missing Dir

---

.goreleaser.yml

This PR:
- Ignores GOOS/GOARCH combinations only supported by go 1.14

ignore non-go 1.14 code

---

README.md
docs/content/install.md

This PR:
- Removes helm v2 references from the documentation
Fixes #463

Remove Helm v2 references

---

cmd/maesh/maesh.go
cmd/prepare/prepare.go
pkg/prepare/fixtures/checkdnsprovider_kubedns.yaml
pkg/prepare/fixtures/checkdnsprovider_no_provider.yaml
pkg/prepare/fixtures/checkdnsprovider_supported_version.yaml
pkg/prepare/fixtures/checkdnsprovider_unsupported_version.yaml
pkg/prepare/fixtures/configurecoredns_already_patched.yaml
pkg/prepare/fixtures/configurecoredns_missing_configmap.yaml
pkg/prepare/fixtures/configurecoredns_not_patched.yaml
pkg/prepare/fixtures/configurekubedns_already_patched.yaml
pkg/prepare/fixtures/configurekubedns_not_patched.yaml
pkg/prepare/prepare.go
pkg/prepare/prepare_test.go

This pull request introduces multiple changes to the prepare package, in order to make it externally usable.
It is a follow-up to the externalization of the prepare code into a package, in PR #454.
The changes are:
* The `CheckCluster` method is renamed to `CheckDNSProvider` to be more explicit on its actual purpose/logic.
* The `CheckCluster` method now returns an enum representing the DNS provider if it is valid, instead of returning a boolean. This is necessary to use the newly split DNS patching code.
* Bringing back the bugfix previously introduced in #349 that was never merged.
* Functions are split into smaller logic blocks, and some more helpers are added (`isPatched`, for example, that checks whether a deployment has the `maesh-patched` label in its metadata).
* The code that …

Refactor `prepare` package for external use

---

pkg/controller/service.go

This PR fixes the port-mapping cleanup method so it doesn't print a warning when cleaning up an HTTP service.
The service mode (http or tcp) wasn't checked. The TCP state table, being used only for TCP, when an HTTP service was cleaned up, a warning was displayed saying we couldn't remove a port mapping. This PR makes sure we are doing this only for TCP services. No cleanup is required on HTTP services.

Fix port-mapping cleanup for HTTP services

---

docs/content/install.md

This PR:
- Adds a note that building from source is for dev only, and is not a supported installation method
Fixes #336

add source build note

---

.travis.yml

This PR:
- Updates Travis to use Go 1.14 for builds
- Updates unused/unneeded keys/configs from https://config.travis-ci.com/explore

Update Travis to build on Go 1.14

---

docs/content/api.md
docs/content/configuration.md
docs/content/examples.md
docs/content/index.md
docs/content/install.md
docs/content/quickstart.md

This PR fixes some little typos I've found while reading the documentation and the `helm documentation` link reported by the HTML checker on `make`.

Fix documentation typos

---

.semaphore/semaphore.yml

Fixes #481.
Currently, every job downloads Go dependencies and build Maesh. This PR uses the available [Semaphore CI cache](https://docs.semaphoreci.com/essentials/caching-dependencies-and-directories/#cache-restore-keysecond-key) to avoid unnecessary work.
Note: `helm` and `k3d` dependencies are not cached. To cache these dependencies, we have to use a [custom container](https://docs.semaphoreci.com/ci-cd-environment/custom-ci-cd-environment-with-docker/#building-a-minimal-docker-image-for-semaphore) which seems a bit unnecessary (`helm` and `k3d` installations seem to be fast).
WDYT?

Add semaphore build cache

---

.semaphore/semaphore.yml

Fixes #501.
This PR fixes the make target used to run the ACL integration test suites to use the Semaphore CI build cache.

Use semaphore build cache when running ACL integration test suites

---

pkg/prepare/prepare.go

This PR fixes a discrepancy in the `Preparer` interface which was misleading and let to two mistakes already where arguments were inverted and a lot of time lost.

Fix discrepancy in prepare interface

---

pkg/provider/provider.go
pkg/topology/builder.go

Pods with no IP are filtered out in the `TopologyBuilder`. When collecting the different pods for a `TrafficTarget`, we are referring to pods which can have been excluded. This is done without checking if the key is in the map, leading to a panic.
This PR intent to be more protective when accessing a map element. 
In the same time, log message and errors have been cleaned up so they don't mention two times the same information and use the `Key` format everywhere instead of "namespace/name".
This can be hard to reproduce as it occurs only when the Provider gets triggered and the Pod informers don't already have pods with an IP assigned. The best way to reproduce this bug is to create many pods at the same time.
* Install Maesh
* Create many pods
* There shouldn't have any panic, even when …

Fix panic when pod IP is not yet assigned

---

docs/mkdocs.yml

Fixes #506.
This PR fixes the broken edit link in the documentation and updates the documentation copyright year.

Fix broken edit link in the documentation

---

helm/chart/maesh/templates/mesh/mesh-daemonset.yaml

Fixes #515.
This PR disables the mesh proxy dashboard in the Helm chart.

Disable mesh proxy dashboard in Helm chart

---

docs/content/install.md
docs/content/migration/helm-chart.md
docs/content/migration/maesh-v1.md
docs/mkdocs.yml
docs/scripts/verify.sh
helm/chart/maesh/Guidelines.md
helm/chart/maesh/templates/controller/controller-deployment.yaml
helm/chart/maesh/values.yaml
integration/acl_enabled_test.go
integration/helm_test.go
integration/integration_test.go
integration/kubedns_test.go
integration/resources/values.yaml

Fixes #502.
This PR removes the deprecated SMI option in the Helm chart.
This PR removes also the Traefik EE reference in the Helm chart guidelines.

Remove deprecated SMI option in the Helm chart

---

helm/chart/maesh/templates/controller/controller-deployment.yaml

This PR:
- Adds the UDP port limit configuration to the controller deployment in the Helm chart.

Fix missing UDP port limit config in Helm chart

---

helm/chart/maesh/templates/controller/controller-deployment.yaml

This PR:
- Removes the unused env variable named `POD_IP` in the Helm chart

Remove unused env variable POD_IP in Helm chart

---

helm/chart/maesh/templates/dns/coredns/coredns-configmap.yaml

This PR:
- Adds custom namespace to helm coreDNS rewrite template
Fixes #549
Part of me would want to have code de-duplication here, but I don't think that it is feasible given how golang parses multi-line strings, and how picky coreDNS is with indentation/whitespace.

Add custom namespace to helm rewrite

---

docs/content/api.md

This PR:
- Removes the documentation for the deployment API endpoint removed in #525.

Remove deployment api endpoint documentation

---

pkg/controller/service.go

This PR fixes a regression on the `ShadowServiceManager.Update`. The new port gets allocated before we clean up the port mapping.
* Deploy maesh with a limited set of TCP port (like 1)
* Deploy a service which exposes a port (`8080`)
* Update the service and replace the exposed port by another one (`8081`)
* Check the tcp-state-table configMap and make sure there's a single port allocated on port (`10000` and not `10001`)
This regression happened in https://github.com/containous/maesh/pull/531

Cleanup port mapping before getting a new port

---

cmd/configuration.go
cmd/maesh/maesh.go
cmd/prepare/prepare.go
cmd/proxy/proxy.go
docs/content/configuration.md
docs/content/migration/helm-chart.md
docs/content/migration/maesh-v1.md
helm/chart/maesh/templates/controller/controller-deployment.yaml
helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
helm/chart/maesh/values.yaml
integration/integration_test.go

This PR:
- Fixes a panic issue if the log level is not defined in the `proxy` cmd configuration.
- Adds a new `logLevel` configuration property to the `maesh` and `prepare` cmds.
- Adds a new `logLevel` property to the Helm chart and removed the older ones for consistency.
Fixes #520.
* Helm install with a custom log level for the `controller`:
```
helm install maesh helm/chart/maesh --set controller.logLevel=debug
```
* Helm install with a custom log level for the `proxies`:
```
helm install maesh helm/chart/maesh --set mesh.logLevel=debug
```
To be consistent the `logLevel` configuration should also be added to the new `cleanup` command in #538.
Maybe we could also add a global Helm `logLevel` option to configure the `controller` and `proxies` log level globally?

Add log level configuration property to commands

---

cmd/cleanup/cleanup.go
cmd/configuration.go
cmd/maesh/maesh.go
helm/chart/maesh/templates/controller/controller-deployment.yaml
helm/chart/maesh/templates/controller/hooks/cleanup-hook.yaml
pkg/cleanup/cleanup.go
pkg/cleanup/cleanup_test.go
pkg/cleanup/fixtures/mock.yaml
pkg/controller/service.go
pkg/controller/service_test.go

This PR:
- Adds a cleanup command
- Adds cleanup functionality to purge created shadow services from the cluster on helm delete
Fixes #487

Add Cleanup Command

---

pkg/controller/controller.go
pkg/controller/handler.go
pkg/k8s/constants.go
pkg/provider/provider.go
pkg/provider/provider_test.go

This PR:
- Removes some unused properties and methods.
- Removes the forced configuration rebuild on `mesh` pods events.
- Triggers a configuration rebuild when pod events are received in ACL mode.
Fixes #513.
- Build and install Maesh with ACL mode enabled.
- Deploy the attached [resources](https://github.com/containous/maesh/files/4586145/issue-513.zip).
- Remove/Add the client resource to trigger dynamic config updates (which does not work well on master).
I've added a check to the `onAdd`, `onUpdate` and `onDelete` handler methods to make sure that we're not rebuilding the dynamic conf if the event should be ignored. Previously, only the service or endpoint events were filtered but we should do the same for `TrafficTarget` and so on.
As `proxy` nodes are now pulling the configuration …

Rebuild dynamic configuration on pod events

---

cmd/maesh/maesh.go
cmd/prepare/prepare.go
integration/integration_test.go
pkg/controller/controller.go
pkg/prepare/prepare.go
pkg/proxy/provider/http/http.go

This PR:
- Capitalizes some log messages for consistency.
- Replaces `%w` in some error log messages which cause ugly log messages:
```
Failed to get config from endpoint: %!w(*fmt.wrapError=&{unable to get data from...
```

Cleanup log messages

---

docs/content/configuration.md
pkg/topology/builder.go
pkg/topology/builder_test.go

This PR:
- Adds a check for an empty destination namespace in traffictargets during load
- Adds test to ensure empty destination namespaces are filled with the namespace of the traffictarget.
Fixes #546
We may want to look at a "validate resource" method in the future, but I think for now it can be avoided as there is not a lot of validation required.

Add destination namespace check in indexer

---

.travis.yml

This PR:
- Backports the fix to increase the goreleaser timeout on branch `v1.2`

Increase goreleaser build timeout

---

.goreleaser.yml

This PR:
- Disables binary builds that don't make sense
This should decrease deploy time, and hopefully fix some deploy issues

Disable non-used builds

---

pkg/api/api.go
pkg/controller/controller.go
pkg/provider/provider.go

This PR:
- Removes the unnecessary `timer` in the controller loop.
- Enables the controller readiness endpoint as soon as the informers are started and synced.
Fixes #565.
As described, the `controller` is now marked as ready when the informers are started. Therefore, the mesh proxies will be able to fetch a default config even if no events are received because of an empty cluster. This default config enables the proxy readiness endpoint, which indicates that the link between the controller and the proxy is ready.
* Create an empty cluster with kind for example.
* Install Maesh with Helm. If you're using kind, you should ignore the `local-path-storage` ns.
* Maesh controller and proxy pods should be marked as ready.

Refine the controller readiness status

---

pkg/controller/controller.go
pkg/controller/handler.go

This PR:
- Removes the unneeded `createMeshServices` method in the controller.
When informers are started, they will emit an `Add` event for every watched resource added to the cache. So, we will receive an event for every `service` created by the user and create the corresponding `shadow service` if needed. Therefore, the `createMeshServices` method in the controller is not needed.

Remove unneeded createMeshServices method in controller

---

pkg/api/api_test.go
pkg/cleanup/cleanup_test.go
pkg/controller/controller_test.go
pkg/k8s/client_mock.go
pkg/prepare/prepare_test.go

This PR:
- Adds `t *testing.T` to clientmock for logging
Fixes #578

Add testing to client mock

---

.golangci.toml
Dockerfile
cmd/context.go
cmd/proxy/proxy.go
integration/acl_disabled_test.go
integration/acl_enabled_test.go
integration/coredns_test.go
integration/helm_test.go
integration/integration_test.go
integration/kubedns_test.go
integration/try/condition.go
pkg/api/api.go
pkg/controller/controller.go
pkg/controller/service.go
pkg/controller/service_test.go
pkg/k8s/client.go
pkg/k8s/client_mock.go
pkg/prepare/prepare.go
pkg/provider/provider.go
pkg/provider/rule.go
pkg/proxy/provider/http/http.go
pkg/topology/builder.go

This PR:
- Updates golangci-lint to v1.27.0
- Resets gocognit setting to proper value
- Refactors methods to pass proper linting
Fixes #550

Upgrade golangci-lint and refactor to meet proper linting settings

---

helm/chart/maesh/charts/metrics/dashboards/traefik.json

This PR:
- updated dashboard for traefik v2 metric naming schema
* View dashboard in Grafana
/na

Update grafana dashboard for traefik v2 metric naming schema

---

integration/integration_test.go
integration/try/try.go
pkg/cleanup/cleanup.go
pkg/cleanup/cleanup_test.go
pkg/controller/controller.go
pkg/k8s/client.go
pkg/k8s/client_mock.go
pkg/prepare/prepare.go
pkg/prepare/prepare_test.go

This PR:
- Adds checks to determine if an in-cluster or external-cluster config needs to be built
- Adds logging for what client is being built
Fixes #580
The warning comes from: https://github.com/kubernetes/client-go/blob/v0.17.4/tools/clientcmd/client_config.go#L543
Where an in-cluster config is built if the args are not present. We can do the check beforehand, and return the same client before calling this method, and skip that warning altogether.

Build kubernetes clients separately

---

pkg/topology/builder.go
pkg/topology/builder_test.go
pkg/topology/testdata/topology-traffic-target-service-port-mismatch.json
pkg/topology/topology.go

This PR fixes a bug that happen when a TrafficTarget is applied on more than one Service and one of them is causing an error: If the `TrafficTarget.destination.port` is not present on the targeted service an error gets logged and it won't process next services.
Fixes #581 
In order to fix this behavior, instead of exiting the function on the first error, we just skip the Service.
- Deploy 2 Service:
- One which expose port 80
- One which expose port 8080
- Define a TrafficTarget with a destination port = 80
- Update the TrafficTarget to trigger update (such as modifying the spec of a HTTPRouteGroup)
You should see one router for the traffic target in the dynamic config.

Fix incomplete topology when destination port is not found

---

docs/content/configuration.md
docs/content/examples.md

This PR:
- Fixes the broken SMI specification links in the documentation.
The SMI specification repository now contains a file for each API version. I've updated the broken links accordingly to the API version supported by Maesh.

Fix broken SMI specification links in the documentation

---

cmd/configuration.go
helm/chart/maesh/Guidelines.md
helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
helm/chart/maesh/values.yaml
pkg/proxy/provider/http/http.go

This PR:
- Adds default values for the `pollInterval` and `pollTimeout` configuration properties.
Fixes #597.

Add default config values for pollInterval and pollTimeout

---

helm/chart/maesh/Chart.yaml
helm/chart/maesh/templates/_helpers.tpl
helm/chart/maesh/templates/controller/controller-deployment.yaml
helm/chart/maesh/templates/controller/hooks/cleanup-hook.yaml
helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
helm/chart/maesh/values.yaml

This PR:
- Adds missing dots to Helm comments.
- Formats and adds properties to Helm `Chart.yaml`.
- Adds a Helm option to configure the `logLevel` globally (the `logLevel` defined for the controller or mesh component has precedence).
Fixes #560.

Add Helm option to configure logging level globally

---

cmd/maesh/maesh.go
pkg/annotations/annotations_test.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/controller/handler.go
pkg/controller/handler_test.go
pkg/controller/service.go
pkg/controller/service_test.go
pkg/k8s/portmapping.go
pkg/k8s/portmapping_test.go
pkg/k8s/service.go
pkg/provider/provider_test.go

This PR:
- Removes unused code.
- Renames some test packages for consistency.
- Reworks the controller loop to use a work queue.
- Reworks the `ShadowServiceManager` to make it `idempotent`.
Fixes #562.
To fix #514, the TCP tables must be built from the `informers` cache which requires some synchronisation before starting the events processing. As discussed, to prepare the work on #514, I've reworked the controller loop to use a work queue which allows enqueueing before processing events.
By design, work queue keys are unique. So, if we receive a lot of events with the same work key, only one will be present in the queue at a time. This would avoid us some unnecessary work if we received a lot of events which require to rebuild the configuration, for example.
Something to keep in mind is …

Rework controller loop to use a work queue

---

helm/chart/maesh/templates/dns/coredns/coredns-configmap.yaml
integration/testdata/kubedns/coredns.yaml
pkg/dns/dns.go
pkg/dns/dns_test.go
pkg/dns/testdata/configurekubedns_already_patched.yaml
pkg/dns/testdata/configurekubedns_not_patched.yaml
pkg/prepare/prepare.go

This PR:
- Modifies the `ConfigureCoreDNS` method to allow for a specified namespace within which to patch CoreDNS
- Leverages the above method to modify our custom coreDNS implementation when kubeDNS is used.
Fixes #593 
By patching our own coreDNS, we still have to restart the pods, and do incur a small delay before the DNS resolution is ready, but that is minimal.

Patch our CoreDNS implementation in kube-dns mode

---

helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
helm/chart/maesh/templates/mesh/mesh-rbac.yaml
helm/chart/maesh/templates/mesh/mesh-sa.yaml

This PR:
- Fixes the `mesh` pods startup.
- Fixes the labels used to check that the `jaeger-agent` service is ready.
- Adds the missing rights to the `mesh` pods to allow `jaeger-agent` readiness check.
- This bug is a side effect of #609 because `k8s-wait-for` is now working properly. 
- It's not necessary to add the `namespace` to the check because the `jaeger-agent` service is in the Maesh namespace.

Fix jaeger init container

---

helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
helm/chart/maesh/values.yaml

This PR:
- Adds configurable annotations for Mesh deployment, and mesh pods
Fixes #612

Add Helm keys to configure annotations for mesh deployment and pods

---

docs/content/install.md
docs/content/migration/helm-chart.md
helm/chart/maesh/templates/controller/controller-deployment.yaml
helm/chart/maesh/values.yaml

This PR:
- Moves the defaultMode configuration to be global
Fixes #605
We may want to introduce a `global` key similar to Traefik's config, to handle these values, as they seem to be piling up.

Move the defaultMode Helm key to be global

---

pkg/controller/controller.go
pkg/k8s/ignore.go
pkg/k8s/ignore_test.go
pkg/topology/builder.go

This PR update the IgnoreWrapper so it ignores Services of type `ExternalName`.
Fixes #618 
In the same time, I fixed an issue in the IgnoredWrapper on the way we handled ignored services. We weren't checking the type of the object, so if a pod had the same name as an ignored service we would have ignored it.
Some deadcode have also been removed.
- `make test`

Ignore ExternalName services

---

pkg/dns/dns.go

This PR:
- Returns an `errors.New` instead of wrapping a nil error in the log message
> no supported DNS service available for installing maesh: %w
Fixes #633
* `make test`
* Install Maesh without coredns:
```
k3d create --server-arg --no-deploy="traefik" --server-arg --no-deploy=coredns
```
* Install Maesh using helm
* Log at the logs of the init container
Once fixed, the output become:
```
$> kubectl logs -n maesh pod/maesh-controller-7577cdfdb-f6j8t -c maesh-prepare
time="2020-06-16T08:45:11Z" level=info msg="Configuration loaded from flags."
time="2020-06-16T08:45:11Z" level=debug msg="Starting maesh prepare..."
time="2020-06-16T08:45:11Z" level=debug msg="Using masterURL: \"\""
time="2020-06-16T08:45:11Z" level=debug msg="Using kubeconfig: \"\""
time="2020-06-16T08:45:11Z" level=info …
```

Stop wrapping nil error when patching DNS

---

pkg/topology/builder.go
pkg/topology/builder_test.go
pkg/topology/testdata/topology-traffic-split-traffic-target.json
pkg/topology/testdata/topology-traffic-target.json
pkg/topology/topology.go

This PR:
- Checks if there is already a TrafficSplit on a service before adding a second one.
- Checks if there is already a TrafficSplit on a service before adding a TrafficTarget.
- Update the tests to cover these cases
Fixes #635 
* `make test`
* Manually by applying multiple traffic-split on the same service or a traffic-split + a traffic-target on the same service.

Stop accepting multiple TrafficSplits or both TrafficSplit and TrafficTarget on the same Service

---

docs/content/migration/maesh-v1.md

This PR:
- Fixes typos in the migration documentation.

Fix typos in migration documentation

---

pkg/dns/dns.go

This PR fixes #638 by adding a `WithMaxRetries` to the call to `backoff.Retry` call in the DNS patching code.
* Try to run the `prepare` command on a cluster which does not have a `coredns` service
* It should fail after 2 minutes and log the appropriate error

Add a max retry for getting coredns service

---

docs/content/install.md
docs/content/migration/helm-chart.md

This PR:
- Fixes the KubeDNS support wording.
- Adds a migration documentation for Prometheus and Grafana services.

Add migration documentation for Prometheus and Grafana services

---

pkg/api/api.go
pkg/controller/controller.go
pkg/controller/service.go
pkg/provider/provider.go
pkg/provider/provider_test.go
pkg/provider/testdata/acl-disabled-http-basic-config.json
pkg/provider/testdata/acl-disabled-http-basic-topology.json
pkg/provider/testdata/acl-disabled-tcp-basic-config.json
pkg/provider/testdata/acl-disabled-tcp-basic-topology.json
pkg/provider/testdata/acl-disabled-udp-basic-config.json
pkg/provider/testdata/acl-disabled-udp-basic-topology.json
pkg/provider/testdata/acl-enabled-http-basic-config.json
pkg/provider/testdata/acl-enabled-http-basic-topology.json
pkg/provider/testdata/acl-enabled-tcp-basic-config.json
pkg/provider/testdata/acl-enabled-tcp-basic-topology.json
pkg/topology/builder.go
pkg/topology/builder_test.go
pkg/topology/topology.go
pkg/topology/topology_test.go

This PR:
- Adds the support for named TargetPort in service resources.
- Fixes the error message returned when a service port mapping fails.
- Fixes the API readiness logging format.
Fixes #517
In the Kubernetes [documentation](https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service):
> Port definitions in Pods have names, and you can reference these names in the targetPort attribute of a Service. This works even if there is a mixture of Pods in the Service using a single configured name, with the same network protocol available via different port numbers. This offers a lot of flexibility for deploying and evolving your Services.
* make test

Support named TargetPort in service resources

---

cmd/maesh/maesh.go
pkg/controller/portmapping.go
pkg/controller/service.go
pkg/controller/service_test.go
pkg/provider/provider.go

This PR makes sure the HTTP, TCP and UDP port limits are enforced correctly. There was a mismatch on how HTTP port limit was handled compared to TCP and UDP. 
For HTTP, TCP and UDP, test the following
- Install Maesh with a limit set to 1. Make sure we can only use 1 port
- Install Maesh with a limit set to 3. Make sure we can only use 3 ports.

Fix HTTP/TCP/UDP port limits

---

cmd/maesh/maesh.go
pkg/controller/controller.go

This PR:
- Ensure that the worker goroutine is finished before exiting the controller loop.
Fixes #655
* make test

Wait for worker goroutine termination before exiting controller loop

---

pkg/dns/dns.go
pkg/dns/dns_test.go
pkg/dns/testdata/configurecoredns_already_patched.yaml
pkg/dns/testdata/configurecoredns_custom_already_patched.yaml
pkg/dns/testdata/configurecoredns_custom_not_patched.yaml
pkg/dns/testdata/configurecoredns_not_patched.yaml
pkg/dns/testdata/configurekubedns_already_patched.yaml
pkg/dns/testdata/configurekubedns_not_patched.yaml
pkg/dns/testdata/configurekubedns_optional_configmap.yaml
pkg/dns/testdata/restorecoredns_custom_not_patched.yaml
pkg/dns/testdata/restorecoredns_custom_patched.yaml
pkg/dns/testdata/restorecoredns_not_patched.yaml
pkg/dns/testdata/restorecoredns_patched.yaml
pkg/dns/testdata/restorekubedns_already_patched.yaml
pkg/dns/testdata/restorekubedns_not_patched.yaml

This PR:
- Cleanup the KubeDNS patching code.
- Fixes the KubeDNS patching code to create the `kube-dns` ConfigMap if it is optional and not yet created. For example, in a Kubernetes cluster deployed with `kops`, the `kube-dns` ConfigMap is optional and not created by default.
Fixes #652
* make test

Create optional kube-dns configmap if needed

---

go.mod
go.sum

This PR:
- Upgrade Traefik dependency version to v2.2.3 
Fixes #669

Upgrade Traefik dependency version to v2.2.3

---

pkg/topology/builder.go

This PR fixes the Topology Builder so it doesn't output the following error message anymore:
```
Unable to find Pod \"@\" for WhitelistMiddleware from Traffic Target 
```
The issue was caused by an `[]Key` allocated with a specific size but keys were added to it conditionally. 
Fixes #599 
* Install Maesh
* Apply a Service and a Deployement with many replicas (worked with 10 replicas)
* You shouldn't see this error in the controller's logs.

Fix unable to find Pod "@"

---

pkg/topology/builder.go
pkg/topology/builder_test.go
pkg/topology/testdata/topology-traffic-split-traffic-target.json

When evaluating a TrafficTarget, targeted services should all be evaluated, even if one of them already has a TrafficSplit attached to it.
This PR fixes a mistakes in the `evaluateTrafficTarget` method of the Topology builder. The function, and so the loop get exited immediately if one of the services already has a TrafficSplit. Instead it should just skip this service and continue on the next one.
Fixes #675 
* `make test`

Evaluate all services targeted by a TrafficTarget even if one of them already has a TrafficSplit

---

docs/content/migration/helm-chart.md
helm/chart/maesh/templates/controller/controller-deployment.yaml
helm/chart/maesh/values.yaml
integration/testdata/values.yaml

This PR:
- Removes the deprecated option `mesh.defaultMode` in the Helm chart.
Fixes #681.

Remove deprecated option mesh.defaultMode in the Helm chart

---

go.mod
go.sum
pkg/controller/service.go
pkg/controller/service_test.go

This PR:
- Adds [go-version](https://github.com/hashicorp/go-version#readme) dependency.
- Uses the Kubernetes server `semver` to check if topology keys are supported.
- Fixes a parsing error when the Kubernetes server `minor` version contains a `+`, see https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/version/base.go#L43
Fixes #678.
* make test

Use Kubernetes semver to add topology keys if supported

---

go.mod
go.sum

This PR:
- Upgrades Traefik dependency version to v2.2.7
Fixes #687 
* Make test

Upgrade Traefik dependency version to v2.2.7

---

integration/coredns_test.go
integration/testdata/coredns/coredns.yaml
integration/testdata/coredns/corednssafe.yaml
pkg/dns/dns.go
pkg/dns/dns_test.go
pkg/dns/testdata/configurecoredns_17.yaml
pkg/dns/testdata/configurecoredns_already_patched.yaml
pkg/dns/testdata/configurecoredns_custom_already_patched.yaml
pkg/dns/testdata/configurecoredns_custom_not_patched.yaml
pkg/dns/testdata/configurecoredns_not_patched.yaml
pkg/dns/testdata/configurekubedns_already_patched.yaml
pkg/dns/testdata/configurekubedns_not_patched.yaml
pkg/dns/testdata/configurekubedns_optional_configmap.yaml

This PR:
- Removes the `upstream` keyword in the CoreDNS config if version is greater than `1.7` 
Fixes #685 
* make test

Fix CoreDNS config if version is greater than or equal to 1.7

---

helm/chart/maesh/templates/dns/coredns/coredns-configmap.yaml
helm/chart/maesh/templates/dns/coredns/coredns-deployment.yaml
helm/chart/maesh/templates/dns/coredns/coredns-rbac.yaml
helm/chart/maesh/templates/dns/coredns/coredns-sa.yaml

This PR:
- Upgrade CoreDNS to 1.7.0 in Helm Chart
- Rename CoreDNS ClusterRole and ClusterRoleBinding in Helm Chart
Fixes #643
Fixes #646 
Removed `upstream` in CoreDNS configuration as it's causing an error. It last mentioned in [1.5.1](https://github.com/coredns/coredns/tree/6c33397d29f6f856e3a197177e63d1bc5341ab0d/plugin/kubernetes#stubdomains-and-upstreamnameservers) and removed since [1.5.2](https://github.com/coredns/coredns/tree/d933f635af392fb7b7938857576f460741151e46/plugin/kubernetes#stubdomains-and-upstreamnameservers).
Using name `maesh-coredns-role` and `maesh-coredns` for consistency with other ClusterRole and ClusterRoleBinding.
```
maesh-controller-role
maesh-coredns-role
maesh-mesh-role
```
```
maesh-controller
maesh-coredns
maesh-mesh
```

Upgrade CoreDNS component in Helm Chart

---

helm/chart/maesh/charts/metrics/templates/grafana-pdb.yaml
helm/chart/maesh/charts/metrics/templates/grafana.yaml
helm/chart/maesh/charts/metrics/templates/prometheus-pdb.yaml
helm/chart/maesh/charts/metrics/templates/prometheus.yaml
helm/chart/maesh/charts/metrics/templates/rbac.yaml
helm/chart/maesh/charts/metrics/templates/storage.yaml
helm/chart/maesh/charts/tracing/templates/jaeger-deployment.yaml
helm/chart/maesh/charts/tracing/templates/jaeger-pdb.yaml
helm/chart/maesh/charts/tracing/templates/jaeger-sa.yaml
helm/chart/maesh/charts/tracing/templates/jaeger-services.yaml
helm/chart/maesh/templates/controller/controller-deployment.yaml
helm/chart/maesh/templates/controller/controller-pdb.yaml
helm/chart/maesh/templates/controller/controller-rbac.yaml
helm/chart/maesh/templates/controller/controller-sa.yaml
helm/chart/maesh/templates/controller/hooks/cleanup-hook.yaml
helm/chart/maesh/templates/dns/coredns/coredns-configmap.yaml
helm/chart/maesh/templates/dns/coredns/coredns-deployment.yaml
helm/chart/maesh/templates/dns/coredns/coredns-rbac.yaml
helm/chart/maesh/templates/dns/coredns/coredns-sa.yaml
helm/chart/maesh/templates/dns/coredns/coredns-service.yaml
helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
helm/chart/maesh/templates/mesh/mesh-pdb.yaml
helm/chart/maesh/templates/mesh/mesh-rbac.yaml
helm/chart/maesh/templates/mesh/mesh-sa.yaml
helm/chart/maesh/templates/mesh/mesh-service.yaml
pkg/controller/controller.go

This PR updates the labels in resources defined in the Helm Chart:
- Harmonize them to only use `app` and `component`. This will allow to ease the implementation of #693
- Add a `app: maesh` label on coredns files to make sure we ignore this service and not create a shadow-service
Fixes #692, #690 
* Install Maesh and make sure Jaeger and Grafana integration still works.

Prevent shadow-service creation for CoreDNS and a custom release name

---

go.mod

This PR removes the unused `github.com/Azure/go-autorest` dependency.
* make test
You can check that the dependency is not required anymore with `go mod why -m github.com/Azure/go-autorest`

Remove unused Azure/go-autorest dependency

---

pkg/provider/provider.go
pkg/provider/provider_test.go
pkg/provider/rule.go
pkg/provider/testdata/acl-enabled-http-route-group-config.json
pkg/provider/testdata/acl-enabled-http-route-group-topology.json
pkg/provider/testdata/acl-enabled-tcp-basic-topology.json
pkg/topology/builder.go
pkg/topology/builder_test.go
pkg/topology/testdata/topology-spec-with-empty-match.json
pkg/topology/testdata/topology-traffic-split-traffic-target.json
pkg/topology/testdata/topology-traffic-target.json
pkg/topology/topology.go

This PR adds support for header-based filtering on TrafficTargets. As described in the specification, an HTTPRouteGroup can define a set of headers that must match to pass through.
https://github.com/servicemeshinterface/smi-spec/blob/master/apis/traffic-specs/v1alpha3/traffic-specs.md#http-header-filters
```
kind: HTTPRouteGroup
metadata:
name: the-routes
namespace: default
spec:
matches:
- name: android-insiders
headers:
- user-agent: ".*Android.*"
- cookie: "^(.*?;)?(type=insider)(;.*)?$"
```
* `make test`
* `make test-integration`
* Install maesh and play with this feature. Instruction on how to use this new filter can be found in the specification

Add support for header-based filtering on TrafficTargets

---

pkg/controller/controller.go
pkg/k8s/constants.go
pkg/prepare/prepare.go
pkg/provider/provider.go
pkg/provider/provider_test.go
pkg/provider/rule.go
pkg/provider/testdata/acl-enabled-http-traffic-split-http-route-group-config.json
pkg/provider/testdata/acl-enabled-http-traffic-split-http-route-group-topology.json
pkg/topology/builder.go
pkg/topology/builder_test.go
pkg/topology/testdata/topology-traffic-split-specs.json
pkg/topology/testdata/topology-traffic-split-traffic-target.json
pkg/topology/topology.go

This PR:
- Add new property `Rules` in the `TrafficSplit` struct
- Build SMI specs rules for each `TrafficSplit` in the TopologyBuilder.
- Update topology tests
Fixes #598 
- `make test`
- Look at the specification (split.v1alpha3) and play with the new feature.

Add support for TrafficSplit filtering

---

cmd/context.go
cmd/maesh/maesh.go
pkg/controller/controller.go

Fix a bug in `cmd/maesh` package where a WaitGroup was getting stuck forever. If the `controller` failed after the program received a signal (e.g. CTRL-C), the error couldn't be sent to the error chan and would block forever.
Fixes #702 
* Run locally the controller with the `MAESH_KUBECONFIG` variable set to a k8s cluster with no SMI CRDs. After few seconds, send a signal. It should stop immediately.

Fix controller signal handling

---

pkg/controller/controller.go

This PR fixes an issue introduced in which causes the controller to stop after 10s. 
* Start Maesh and apply a manifest containing a service. You should see a shadow-service in maesh namespace.

Fix timeout on start informers

---

pkg/dns/dns.go
pkg/k8s/client.go

This PR reworks the log messages of the prepare command. So logs which are considered useful for debugging have been move to the DEBUG level. Some context has been added to the logs.
Fixes #660 
* run `maesh prepare` a local cluster, try with the `--logLevel` option

Improve prepare command logs

---

docs/content/compatibility.md
helm/chart/maesh/templates/controller/controller-rbac.yaml
helm/chart/maesh/templates/coredns/coredns-rbac.yaml

This PR:
- Updates the supported versions of Kubernetes in the documentation because of the [1.19](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#v1190) release.
- Updates the RBAC apiVersion which has been deprecated since version [1.17](https://v1-17.docs.kubernetes.io/docs/setup/release/notes/#deprecations-and-removals).

Update apiVersion of RBAC resources in Helm

---

.golangci.toml
Dockerfile
integration/k3d/k3d.go
pkg/api/api_test.go
pkg/controller/controller.go
pkg/dns/dns_test.go
pkg/k8s/client_mock.go
pkg/topology/builder_test.go

This PR:
- Upgrades `golangci-lint` version to v1.30.
* make check

Upgrade golangci-lint version to v1.30

---

helm/chart/maesh/templates/controller/controller-service.yaml
helm/chart/maesh/templates/coredns/coredns-deployment.yaml
helm/chart/maesh/templates/coredns/coredns-service.yaml
helm/chart/maesh/templates/mesh/mesh-service.yaml

This PR:
- Adds app and release selector to the controller service
- Adds release selector to the mesh service
- Adds release selector to maesh coredns pods
Fixes #725

Add app and release selector to the controller service

---

.golangci.toml
Dockerfile
pkg/dns/dns.go
pkg/topology/builder.go

This PR:
- Upgrades golangci-lint version to v1.31
* make check

Upgrade golangci-lint version to v1.31

---

go.mod
go.sum

This PR upgrades the Traefik dependency version to `v2.3.0`
* make test

Upgrade Traefik dependency version to v2.3.0

---

cmd/configuration.go
cmd/mesh/mesh.go
cmd/prepare/prepare.go
pkg/controller/controller_test.go

This PR removes the `smi` flag which is now deprecated since v1.2.
* make test

Remove smi flag

---

cmd/cleanup/cleanup.go
cmd/configuration.go
cmd/log.go
cmd/mesh/mesh.go
cmd/prepare/prepare.go

This PR removes the --debug deprecated flag.
Fixes #748
* `make test`

Remove deprecated debug flag

---

cmd/mesh/mesh.go
cmd/prepare/prepare.go
pkg/api/api.go
pkg/api/api_test.go
pkg/controller/controller_test.go
pkg/controller/handler_test.go
pkg/controller/service_test.go
pkg/dns/dns_test.go
pkg/k8s/client.go

This PR:
- Returns an error to exit with a code greater than zero in case of a controller or API error.
- Renames all `log` fields, params and vars to `logger`.
Fixes #750

Return an error if the API or controller stops unexpectedly

---

cmd/mesh/mesh.go
docs/content/api.md
integration/testdata/traefik-mesh/controller-acl-disabled.yaml
integration/testdata/traefik-mesh/controller-acl-enabled.yaml
integration/testdata/traefik-mesh/proxy.yaml
pkg/api/api.go
pkg/api/api_test.go
pkg/controller/controller.go
pkg/controller/controller_test.go

This PR:
- Removes the `/api/status/nodes` endpoint
- Removes the `/api/status/nodes/<id>/configuration` endpoint
- Renames the `/api/status/readiness` endpoint into `/api/ready`
- Renames the `/api/configuration/current` endpoint into `/api/configuration`
- Renames the `/api/topology/current` endpoint into `/api/topology`
Fixes #749
* `make test`
* Install Traefik Mesh on a cluster and play with the API

Cleanup API endpoints

---

docs/theme/partials/product-switcher.html

We now have a dedicated docs site for Traefik Pilot at https://doc.traefik.io/traefik-pilot/
This PR adds Pilot to the pull-down menu on the left of the documentation that allows users to easily switch between products.

Add Traefik Pilot to docs switcher menu

---

integration/testdata/acl_enabled/http/6.traffic-target.yaml
integration/testdata/acl_enabled/traffic-split/1.server-split.yaml
pkg/provider/provider.go
pkg/provider/rule.go
pkg/provider/testdata/acl-enabled-http-basic-topology.json
pkg/provider/testdata/acl-enabled-http-route-group-topology.json
pkg/provider/testdata/acl-enabled-http-traffic-split-http-route-group-topology.json
pkg/provider/testdata/acl-enabled-http-traffic-split-topology.json
pkg/topology/builder.go
pkg/topology/testdata/topology-traffic-split-traffic-target.json
pkg/topology/testdata/topology-traffic-target.json
pkg/topology/topology.go

This PR:
- Forbid HTTP traffic if the TrafficTarget doesn't contain an HTTPRouteGroup (according to the specification)
- Remove the HTTPMatches field of the ServiceTrafficTarget struct. Instead, the HTTPRouteGroup.Spec.Matches gets filtered out from every unwanted rules.
Fixes #747 
* `make test`
* Install traefik mesh with acl=true, apply a TrafficTarget with and without an HTTPRouteGroup.

Deny HTTP traffic when no HTTPRouteGroup is given

---

docs/content/compatibility.md

This PR adds the supported SMI spec versions in the Compatibility page of the documentation.
Fixes #768

Add supported SMI spec versions

---

docs/content/compatibility.md
docs/theme/partials/product-switcher.html

This PR:
Merges v1.4 branch into master

 Merge branch v1.4 into master

---

pkg/dns/dns.go
pkg/dns/dns_test.go
pkg/dns/testdata/checkdnsprovider_supported_version_suffix.yaml

This PR fixes an issue where the `traefik-mesh-controller/traefik-mesh-prepare` script would fail if the version of CoreDNS deployed in your environment contains a prefix. This has been seen on AWS EKS, where a build version is present (i.e: `v1.6.6-eksbuild.1`).
As described in the #773 issue, this is due to the way [hashicorp/go-version](github.com/hashicorp/go-version) handles version string when verified using `goversion.NewConstraint(">= 1.3, < 1.8")` as it considers any `-suffix` to be a pre-release version instead of a metadata (expecting a `+suffix` instead). This can be fixed by using the form `version.GreaterThanOrEqual("1.3") && version.LessThan("1.8")`.
Fixes #773
* Deploy an AWS EKS v1.17 environment (which would be deployed with CoreDNS v1.6.6-eksbuild.1)
* Deploy the …

Allow CoreDNS version strings to contain sufixes

---

Dockerfile
tmpl.Dockerfile

Since the recent release of [goreleaser](https://goreleaser.com) [v1.2.1](https://github.com/goreleaser/goreleaser/releases/tag/v1.2.1), the script to install it was removed.
This PR update the script to install goreleaser to use a gist instead.
Have a working CI.

fix: update goreleaser install link to use gist

---

.github/workflows/documentation.yml

Update `seo` tool and use the flag `product`
Currently, all the documentation tiles contain `Site` instead of `Traefik Mesh`

docs: fix product name

---

integration/coredns_test.go
integration/testdata/traefik-mesh/controller-acl-disabled.yaml
integration/testdata/traefik-mesh/controller-acl-enabled.yaml
pkg/dns/dns.go
pkg/dns/dns_test.go
pkg/dns/testdata/checkdnsprovider_coredns_using_label.yaml

This PR updates the CoreDNS detection. Previously we were only looking for the exact deployment name `coredns` in the `kube-system` namespace. The issue was that some Kubernetes distributions (RKE2 for example), use a different name for the CoreDNS deployment.
With this PR, we now look for a deployment having the label `kubernetes.io/name=CoreDNS`, which seems to be the case for most Kubernetes distributions. We still fall back to the old behavior if no deployment is found using the label because `kubeadm` does not add it for example (but it uses the default deployment name).
Unit tests have been updated to cover the new use-case.
If we face more edge-cases like this one, we might want to consider adding a flag so users can directly set the name (and type?) of there DNS provider.

Fix CoreDNS Detection

---

.semaphore/semaphore.yml
Makefile

This pull request fixes the `publish-images` step of the release process by upgrading the seihon version to `v0.9.0` and the base image to `alpine:3.15` as requested in https://github.com/traefik/mesh/pull/818.
It also increases the semaphore machine used for the build to avoid running out of space in the release process.

Fix publish-images step of release process

---

.golangci.toml
Dockerfile
pkg/api/api.go
pkg/provider/provider.go

This pull requests updates golangci-lint to `v1.48.0`.

Update golangci-lint to v1.48.0

---

.golangci.toml
.semaphore/semaphore.yml
Dockerfile
docs/content/contributing/building-testing.md
go.mod
go.sum
tmpl.Dockerfile

This pull request updates the Go version to `go1.19` to be able to obtain security patches from the Go team.

Update to go1.19

---

Makefile
integration/acl_disabled_test.go
integration/acl_enabled_test.go
integration/coredns_test.go
integration/integration_test.go
integration/k3d/k3d.go
integration/kubedns_test.go
integration/testdata/acl_disabled/http/1.server.yaml
integration/testdata/acl_disabled/traffic-split/2.server-v1.yaml
integration/testdata/acl_disabled/traffic-split/3.server-v2.yaml
integration/testdata/acl_disabled/udp/1.server.yaml
integration/testdata/acl_enabled/http/1.server.yaml
integration/testdata/acl_enabled/http/3.server-api.yaml
integration/testdata/acl_enabled/http/4.server-header.yaml
integration/testdata/acl_enabled/traffic-split/1.server-split.yaml
integration/testdata/crds/smi-access.yaml
integration/testdata/crds/smi-specs.yaml
integration/testdata/crds/smi-split.yaml
integration/testdata/kubedns/coredns.yaml
integration/testdata/kubedns/kubedns.yaml
integration/testdata/traefik-mesh/controller-acl-disabled.yaml
integration/testdata/traefik-mesh/controller-acl-enabled.yaml
integration/testdata/traefik-mesh/proxy.yaml
integration/tool/tool.go

This pull request updates the k3d version to `v5.4.4` to be able to run the integration tests locally. 
Because of an issue in k3d, it is not possible to import `amd64` images in a cluster on Apple Silicon. For that reason, the new `--disable-import` flag can be leveraged to run the integration tests on M1 machines.
```shell
$ TESTFLAGS="--disable-import" make test-integration
```

Update k3d to v5.4.4

---

docs/mkdocs.yml

Changes the Copyright text in the documentation.
- Navigate to the `/docs` directory
- Run `make serve`
- Check the documentation at `http://0.0.0.0:8000/traefik-mesh/`
- The year of the copyright is already set for 2023

chore: update copyright text 2023
